### PR TITLE
Update WSGL to match spec

### PR DESCRIPTION
**Pull request by OmarShehata**
Fixes https://github.com/takahirox/online-wgsl-editor/issues/15. I went through and updated the WGSL starter code to fix all warnings.

### CODE REVIEW

**Comment by takahirox** [comment]
Hi, thanks for the PR.

Since Chrome 100 (the current Canary) Chrome seems to start not to accept WGSL `[[foo]]` syntax. While Chrome 97 (the current Chrome) doesn't recognize the new syntax yet.

I want the editor to be able to run on the current Chrome. So how about converting the WGSL for Chrome 100 and newer so far until Chrome 100 will be released? Like

```javascript
// Chrome 100 and newer doesn't seem to accept deprecated WGSL syntax [[foo]]
// But the current Chrome 97 doesn't recognize the new syntax @foo yet.
// So converting the WGSL code for Chrome 100 and newer so far.
if (match && parseInt(match[1]) >= 100) {
  // Replacement logic can be more elegant but I don't mind
  document.getElementById('defaultShader').textContent = 
    document.getElementById('defaultShader').textContent
      .replaceAll('[[', '@')
      .replaceAll(']]', '')
      .replaceAll(', binding', ' @binding');
}
```

**Comment by OmarShehata** [comment]
Ah, yes, I see that comment in the code now. My bad. Thank you for pointing this out. I will update this PR with your suggestion soon.

**Comment by OmarShehata** [comment]
I've updated the PR as suggested. I tested on Chrome 100 that the substitution leads to a shader that works with no warnings. And if/when the syntax changes again the editor will continue to work since the other PR allows compiling when there are warnings.

Thank you @takahirox !

**Comment by takahirox** [comment]
Sorry I didn't clearly write. Please not remove the workaround adding `[[block]]` for Chrome 98 and older. The current Chrome 97 needs it.

Please add the new workaround after the existing one.

**Comment by OmarShehata** [comment]
My bad. Updated the PR now.

I've also marked this as "allow edits by maintainer" so if there's any other tweaks you prefer to make yourself directly to the PR please feel free to do so :)

**Comment by takahirox** [comment]
Looking good, thanks!

**Pull request merged**
